# Generated by Django 4.2 on 2023-05-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
