# Generated by Django 4.2 on 2023-06-07 07:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_price_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('offer_description', models.TextField(blank=True, max_length=500)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_till', models.DateField()),
                ('offer_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.pricefilter'),
            preserve_default=False,
        ),
    ]
