# Generated by Django 4.2 on 2023-05-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='order',
        ),
    ]
