# Generated by Django 4.2 on 2023-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_remove_usercoupon_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='return_comment',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
