# Generated by Django 4.2 on 2023-06-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_returnorder_return_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='return_comment',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
