# Generated by Django 5.0.4 on 2024-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
