# Generated by Django 5.0.4 on 2024-08-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/order_items'),
        ),
    ]
