# Generated by Django 5.0.4 on 2024-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='_product_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
