# Generated by Django 5.0.4 on 2024-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_remove_orderitem__price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/order_items'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
