# Generated by Django 5.0.4 on 2024-08-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_remove_orderitem__price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
