# Generated by Django 5.0.4 on 2024-08-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_price',
        ),
    ]
