# Generated by Django 4.2 on 2023-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
