# Generated by Django 4.2 on 2023-05-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='variation',
        ),
    ]
