# Generated by Django 4.2 on 2023-06-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_wallet_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
